### ISSUE TITLE
[LOTP] Add local GHA

### ISSUE THREAD

**Issue by Talgarr** [boostsecurityio/lotp#56]
# Description of the LOTP tool

If a local github action is used (`uses: .`, `uses: ./.github/actions/`), it is trivial to overwrite it with our own malicious action.

## Configuration file

`action.yml`
`action.yaml`
`Dockerfile`

## Example

```yaml
name: ''
description: ''
author: ''

runs:
  using: 'bash'
  main: 'echo Hello world'
```
